#ifndef TEST_TEST_STATIC_HPP
#define TEST_TEST_STATIC_HPP
#include"test.hpp"
void foo(void)noexcept{
    TEST_STATIC_CHECK(1+1==3);
    TEST_STATIC_CHECK_NOT(1+1==2);
}
#if TEST_HAS_COUNTER
    TEST_STATIC_CHECK(1+1==3);
    TEST_STATIC_CHECK_NOT(1+1==2);
#endif//TEST_HAS_COUNTER
#endif//TEST_TEST_STATIC_HPP
